export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const ADD_FACILITIES = 'ADD_FACILITIES'
export const GET_FACILITIES = 'GET_FACILITIES'
export const DELETE_FACILITIES = 'DELETE_FACILITIES'
export const UPDATE_FACILITIES = 'UPDATE_FACILITIES'
export const LOADING_FACILITIES = 'LOADING_FACILITIES'

export const GET_PRODUCTS = 'GET_PRODUCTS'
export const LOADING_PRODUCTS = 'LOADING_PRODUCTS'
export const ADD_PRODUCTS = "ADD_PRODUCTS"
export const DELETE_PRODUCTS = "DELETE_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"
export const ERROR_PRODUCTS = "ERROR_PRODUCTS"

export const GET_FRUITS = "GET_FRUITS"
export const GET_REVIEW = "GET_REVIEW"
export const ADD_REVIEW = "ADD_REVIEW"
export const DELETE_REVIEW ="DELETE_REVIEW"

export const UPDATE_REVIEW= "UPDATE_REVIEW"

export const GET_CATEGORY = "GET_CATEGORY"

export const ADD_CATEGORY = "ADD_CATEGORY"

export const DELETE_CATEGORY = "DELETE_CATEGORY"

export const UPDATE_CATEGORY = "UPDATE_CATEGORY"
